name: Documentation

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: Sources
          module-name: CombineRequests
          output: Documentation
      - uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: Documentation
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
